/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class AppTest {

    App logic = new App();

    @Test
    public void testCalculateDiscount() {
        assertEquals(15.0, logic.calculateDiscount(1200), 0.01);
        assertEquals(10.0, logic.calculateDiscount(800), 0.01);
        assertEquals(5.0, logic.calculateDiscount(300), 0.01);
    }

    @Test
    public void testGenerateCoupon() {
        String coupon = logic.generateCoupon();
        assertTrue(coupon.startsWith("COUPON-"));
    }

    @Test
    public void testCalculateTotalPrice() {
        assertEquals(110.0, logic.calculateTotalPrice(100.0, 10.0), 0.01);
    }

    @Test
    public void testIsProductAvailable() {
        assertTrue(logic.isProductAvailable(4));
        assertFalse(logic.isProductAvailable(3));
    }

    @Test
    public void testIsValidEmail() {
        assertTrue(logic.isValidEmail("test@example.com"));
        assertFalse(logic.isValidEmail("test.com"));
    }
}

