name: Sonar Scan

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests with Jacoco
        run: ./gradlew test jacocoTestReport

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v3.0.0
        with:
          projectBaseDir: '.'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Upload Jacoco HTML report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-html-report
          path: app/build/reports/jacoco/test/html/index.html


